[tool.poetry]
name = "emulator"
version = "0.1.0"
description = "GameBoy emulator written in Python from pythoninspired.com"
authors = ["Jason K Bellew <796886+macshaggy@users.noreply.github.com>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.10"
hypothesis = "^6.34.2"

[tool.poetry.dev-dependencies]
pycodestyle = "^2.8.0"
<<<<<<< HEAD
=======
ipython = "^8.0.0"
pytest = "^7.0.0"
>>>>>>> main

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "integration",
]
